services:
  - type: web
    name: telegram-voicebot
    runtime: python
    plan: free
    region: frankfurt      # или выбрать другой регион, если нужен
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      # если используешь fallback на OpenAI:
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: "/"
